### ISSUE TITLE
Missing permissions error.

### ISSUE THREAD

**Issue by JulesVan** [lilserf/bot-on-the-clocktower#145]
The bot told me it couldn't grant the relevant roles because it was missing permissions, even though I checked and it does have the Manage Roles permission.

Here's the text that the bot asked me to submit:
Interaction error [Guild: 438365109790965762
Channel: 989174701219799100]
Exception: UnauthorizedException
Message:   Unauthorized: 403 : Missing Permissions
Stack trace:
   at Bot.DSharp.ExceptionWrap.WrapExceptionsAsync[T](Func`1 f) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.DSharp/ExceptionWrap.cs:line 40
   at Bot.DSharp.DSharpMember.RevokeRoleAsync(IRole r) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.DSharp/DSharpMember.cs:line 46
   at Bot.Core.BotGameplay.EndGameForTownAsync(IGuild guild, IRole storytellerRole, IRole villagerRole, IProcessLogger logger) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/BotGameplay.cs:line 381
   at Bot.Core.BotGameplay.EndGameUnsafeAsync(TownKey townKey, IProcessLogger logger) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/BotGameplay.cs:line 363
   at Bot.Core.Interaction.BaseInteractionErrorHandler`1.TryProcessReportingErrorsAsync(TKey key, IMember requester, Func`2 process) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/Interaction/BaseInteractionErrorHandler.cs:line 27

**Comment by magroader** [comment]
Did you drag the "Bot on the Clocktower" role above all the "Villager" / "Storyteller" roles in the roles list for the server?

If that fixes it, we should improve this error message. If not, something else is wrong!

**Comment by JulesVan** [comment]
That fixed it! Thank you for such a prompt response.
