### ISSUE TITLE
Bot on the Clocktower encountered an error

### ISSUE THREAD

**Issue by steini225** [lilserf/bot-on-the-clocktower#147]
Interaction error [Guild: 984570205508362300
Channel: 989931527515304006]
Exception: InvalidOperationException
Message:   Collection was modified; enumeration operation may not execute.
Stack trace:
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Bot.DSharp.DSharpChannel.ClearOverwrites() in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.DSharp/DSharpChannel.cs:line 30
   at Bot.Core.BotGameplay.PhaseNightUnsafe(IGame game, IProcessLogger processLog) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/BotGameplay.cs:line 251
   at Bot.Core.BotGameplayInteractionHandler.<>c__DisplayClass20_0.<<PhaseNightInternal>b__0>d.MoveNext() in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/BotGameplayInteractionHandler.cs:line 105
--- End of stack trace from previous location ---
   at Bot.Core.Interaction.BaseInteractionErrorHandler`1.TryProcessReportingErrorsAsync(TKey key, IMember requester, Func`2 process) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/Interaction/BaseInteractionErrorHandler.cs:line 27

**Comment by magroader** [comment]
@steini225 Is this happening every time or was it a 1-off?

**Comment by magroader** [comment]
@steini225 I think I just submitted a fix, which should go live in a few minutes, but I don't have enough people handy to do a thorough test. Please submit another report if it happens again!

**Comment by steini225** [comment]
this happend everytime if i move the player to night

**Comment by magroader** [comment]
@steini225 Thanks, are you still playing? Is it still happening?

**Comment by steini225** [comment]
im still playing i dont get the error anymore
but the the permissions from the night channel got removes so sometimes channels are not hidden

**Comment by magroader** [comment]
@steini225 I'm not sure what you mean by that, can you post a screen shot here?

**Comment by steini225** [comment]
if you want you can add me at discord so you can see that
Steini225#4400
