### ISSUE TITLE
Bot got stuck, threw exception eventually (when it was restarted perhaps?)

### ISSUE THREAD

**Issue by magroader** [lilserf/bot-on-the-clocktower#151]
Steini225 had the bot get stuck on them:

> i had a vote timer for calling the players back to town
> and no one was moved
> then i tried the expanding options
> then i tried the command /vote

We told the bot to restart and it eventually did and sent them an error:

Bot on the Clocktower encountered an error.

Please consider reporting the error at https://github.com/lilserf/bot-on-the-clocktower/issues and including all the information below:

```
Queue Process [Guild: 984570205508362300
Channel: 990010716167749702]
Exception: UnauthorizedException
Message:   Unauthorized: 401 : Invalid Webhook Token
Stack trace:
   at Bot.DSharp.ExceptionWrap.WrapExceptionsAsync[T](Func1 f) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.DSharp/ExceptionWrap.cs:line 40
   at Bot.Core.Interaction.BaseInteractionQueue1.ProcessQueueAsync(TKey key) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/Interaction/BaseInteractionQueue.cs:line 90
```
Bot on the Clocktower encountered an error.

Please consider reporting the error at https://github.com/lilserf/bot-on-the-clocktower/issues and including all the information below:

```
Queue Process [Guild: 984570205508362300
Channel: 990010716167749702]
Exception: UnauthorizedException
Message:   Unauthorized: 401 : Invalid Webhook Token
Stack trace:
   at Bot.DSharp.ExceptionWrap.WrapExceptionsAsync[T](Func1 f) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.DSharp/ExceptionWrap.cs:line 40
   at Bot.Core.Interaction.BaseInteractionQueue1.ProcessQueueAsync(TKey key) in /home/runner/work/bot-on-the-clocktower/bot-on-the-clocktower/Bot.Core/Interaction/BaseInteractionQueue.cs:line 90
```

So it seems like maybe it was stuck running SOMETHING in the Queue - not sure what - and then an exception was thrown when the bot restarted.

Still not sure how it got stuck in the queue, nor what it was doing. Perhaps we can:
* Add a timeout to cancel the operation
* Log when the timeout hits, and what it was doing when it hit

**Comment by magroader** [comment]
We have long-running tracking now, and we have the bot rebooting once a month to hopefully alleviate this.
