### ISSUE TITLE
Throws exception if someone tries to move to a cottage immediately after they disconnect

### ISSUE THREAD

**Issue by magroader** [lilserf/bot-on-the-clocktower#82]
Someone disconnected from Discord right as/after I did `!night` and I got this error:

Alas, an error has occurred:
```
Traceback (most recent call last):
  File "bot.py", line 1158, in onNight
    await user.move_to(cottage)
  File "/app/.heroku/python/lib/python3.6/site-packages/discord/member.py", line 626, in move_to
    await self.edit(voice_channel=channel, reason=reason)
  File "/app/.heroku/python/lib/python3.6/site-packages/discord/member.py", line 601, in edit
    await http.edit_member(guild_id, self.id, reason=reason, **payload)
discord.errors.HTTPException: 400 Bad Request (error code: 40032): Target user is not connected to voice.
```
(from message `!night`)

**Comment by lilserf** [comment]
Closing this since it's python-specific; if we see the same on C# I'll enter a new issue
